version: '3'
services:
    #Database Service
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: ${POSTGRES_DB}
            TZ: Asia/Ho_Chi_Minh
        volumes:
            - ./postgres/data:/var/lib/postgresql/data/pgdata
        ports: 
            - ${POSTGRES_PORT}:5432
        networks:
            - app-network
    
    #Cache Service  
    cache:
        image: "redis:5.0.8-alpine"
        container_name: cache
        networks:
            - app-network
        ports: 
            - ${CACHE_PORT}:6379
        restart: "on-failure"

#Docker Networks
networks:
    app-network:
      driver: bridge
#Volumes
volumes:
    dbdata:
      driver: local